### ISSUE TITLE
Is there any information how to change response structure?

### ISSUE THREAD

**Issue by glagius** [Insidexa/nestjs-rpc#114]
Came across with a specific format when returning an error from the server.
The response status and message are duplicated in the response and result fields.
Is this how it should be?

Example:
```
{
  jsonrpc: '2.0',
  result: {
    response: {
      statusCode: 400,
      message: 'Connection inactive',
      error: 'Bad Request'
    },
    status: 400,
    message: 'Connection inactive',
    name: 'BadRequestException'
  },
  id: 3
}
```

**Comment by Insidexa** [comment]
@glagius https://www.jsonrpc.org/specification
