### ISSUE TITLE
Many methods

### ISSUE THREAD

**Issue by guzmanf** [Insidexa/nestjs-rpc#50]
hello, my calls methods are contact.insertNew, contact.deleteRecord, contact.XXXX, howto make handler for this methods, best regards

**Comment by Insidexa** [comment]
@guzmanf Hi, thank you for questions. 
In current implementation there is no possibility to use many methods in one handler.

But I’ll try to add this feature soon

**Comment by Insidexa** [comment]
@guzmanf I add feature with multiple RPC handlers per class :)

**Comment by guzmanf** [comment]
> @guzmanf I add feature with multiple RPC handlers per class :)

thanks!, is working perfecticly, best regards
