### ISSUE TITLE
Security, Passport and JWT strategies ?

### ISSUE THREAD

**Issue by guzmanf** [Insidexa/nestjs-rpc#63]
hello friends, for implement security, the method passport and JWT is feasible with then handlers?..best regards

**Comment by Insidexa** [comment]
json rpc is an independent protocol that can be implemented by transport TCP, Websocket, HTTP  
Current implementation use on HTTP, but I have plans for add Websocekt transport.  

You can create guard with NestJS and in Guard check request body contains `token` field.  
For example:
```
{
  "jsonrpc": "2.0",
  "method": "test",
  "id": 2,
  "params": { "token": "tokenPayload", ...otherFields }
}
```

Token field encrypted with secret key on server. You can decrypt token and get from token `payload` with user `id`.   
If token valid -> attach to JSON RPC payload `user` field.

**Comment by guzmanf** [comment]
thanks for the answer, the problem I have is how I implement the guards to validate login access, I have tried the examples and tutorials for the implementation and I always have a 401 error, basically I have changed the controller for the handlers; An example of implementing authentication and guards would be very helpful.

body send:
================================
{
	"jsonrpc": "2.0",
	"method": "Auth.login",
	"id": 1,
	"params": 
		{
			"username": "wafo",
			"password": "master"
		}
}

auth/aut.handlers.ts
-------------------------------
@RpcHandler({ method: 'Auth' })
...
@UseGuards(AuthGuard('local')) ----> alway error 401
@RpcMethodHandler('login')
...

regards

**Comment by Insidexa** [comment]
@guzmanf Its very easy
See example - [JWT](https://github.com/Insidexa/nestjs-rpc/tree/master/samples/auth)
